#!/usr/bin/env bash
#customising a 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

#creating a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replace="listen 80 default_server;\n\terrror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/ var/www/html;\n\t\tinternal;\n\t}"

sudo -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#restart nginx after implementing changes

sudo service nginx restart
